services:
  hello-py:
    build: ./python
    image: cabantoad/hello-pyhton:1.0.0
    ports:
      - 3000:3000
    environment:
      - ENV_VALUE=${ENV_VALUE}

  hello-node:
    build: ./node
    image: cabantoad/hello-node:1.0.0
    ports:
      - 3001:3000
    environment:
      - ENV_VALUE=${ENV_VALUE}

  hello-spring:
    build: ./springboot/hello-spring
    image: cabantoad/hello-spring:1.0.0
    ports:
      - 8080:8080
    environment:
      - ENV_VALUE=${ENV_VALUE}
